4

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -16,6 +16,11 @@ steps:
 - script: dotnet build --configuration $(buildConfiguration)
   displayName: 'dotnet build $(buildConfiguration)'
 
+- script:
+  #!/bin/bash
+  echo "##vso[task.logissue type=error]Something went very wrong."
+  exit 1
+
 - publish: '/home/vsts/work/1/s/bin/Release/net6.0'
   artifact: $(Agent.JobName)_$(AGENT_JOBSTATUS)_$(agent.jobstatus)_BuildLogs_Attempt$(System.JobAttempt)
   displayName: Publish BuildLogs
