Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -16,35 +16,37 @@ stages:
   - job: A1
     steps:
     - script: |
-        echo `date +%Y-%m-%d-%H-%M-%S`
-        dotnet build --configuration $(buildConfiguration)
-      displayName: 'dotnet build $(buildConfiguration)'
-    - bash: |
-        cd '/home/vsts/work/1/s/bin/Release/net6.0'
-        echo $(System.JobAttempt) > temp.json
-      displayName: Create new file   
-    - bash: |
-        cd '/home/vsts/work/1/s/bin/Release/net6.0'
-        rm 'appsettings.json'
-        exit 1
-      condition: ne(variables['System.JobAttempt'], '3')
-      displayName: Fail build if partially successful   
-    - bash: |
-        newValue="Succeeded"
-        echo "##vso[task.setvariable variable=status;]$newValue"
-      displayName: Succeed
-      condition: succeeded()
-    - bash: |     
-        newValue="Failed"
-        echo "##vso[task.setvariable variable=status;]$newValue"
-      displayName: Fail
-      condition: failed() 
-    - bash:
-        echo $(status)
-      displayName: 'echo $(status)'
-      condition: succeededOrFailed()   
-    - publish: '/home/vsts/work/1/s/bin/Release/net6.0'
-      artifact: $(Agent.JobName)_BuildLogs_Artifact$(System.JobAttempt)
-      displayName: Publish BuildLogs
-      continueOnError: true
-      condition: succeededOrFailed()
+          tt =  az pipelines runs artifact list --run-id 91 --org 'https://dev.azure.com/v-wexu0720/' --project 'Test' --query "[].name[1]"
+          echo $(tt)
+    #     echo `date +%Y-%m-%d-%H-%M-%S`
+    #     dotnet build --configuration $(buildConfiguration)
+    #   displayName: 'dotnet build $(buildConfiguration)'
+    # - bash: |
+    #     cd '/home/vsts/work/1/s/bin/Release/net6.0'
+    #     echo $(System.JobAttempt) > temp.json
+    #   displayName: Create new file   
+    # - bash: |
+    #     cd '/home/vsts/work/1/s/bin/Release/net6.0'
+    #     rm 'appsettings.json'
+    #     exit 1
+    #   condition: ne(variables['System.JobAttempt'], '3')
+    #   displayName: Fail build if partially successful   
+    # - bash: |
+    #     newValue="Succeeded"
+    #     echo "##vso[task.setvariable variable=status;]$newValue"
+    #   displayName: Succeed
+    #   condition: succeeded()
+    # - bash: |     
+    #     newValue="Failed"
+    #     echo "##vso[task.setvariable variable=status;]$newValue"
+    #   displayName: Fail
+    #   condition: failed() 
+    # - bash:
+    #     echo $(status)
+    #   displayName: 'echo $(status)'
+    #   condition: succeededOrFailed()   
+    # - publish: '/home/vsts/work/1/s/bin/Release/net6.0'
+    #   artifact: $(Agent.JobName)_BuildLogs_Artifact$(System.JobAttempt)
+    #   displayName: Publish BuildLogs
+    #   continueOnError: true
+    #   condition: succeededOrFailed()
