111111

diff --git a/new-pipelines.yml b/new-pipelines.yml
--- a/new-pipelines.yml
+++ b/new-pipelines.yml
@@ -26,10 +26,6 @@ stages:
     pool:
       vmImage: 'ubuntu-latest'
     steps:
-    # - script: |
-    #     sleep 120
-    #     echo "Done waiting."
-    #   displayName: Wait for 2 minutes
 
     - script: |
         echo $(resources.pipeline.Example.projectID)
@@ -38,5 +34,28 @@ stages:
         echo $(resources.pipeline.Example.runURI)
         echo $(resources.pipeline.Example.sourceBranch)
         echo $(resources.pipeline.Example.sourceCommit)
+
+        if [[ -z "$dotnet_dotnet_build" ]]; then
+          dotnet_dotnet_build=$(az pipelines runs list --branch '$(Build.SourceBranch)' --organization 'https://dev.azure.com/v-wexu0720' --project 'Test' --pipeline-ids '1' --status completed --top 1 --query "[].id" --output tsv)
+        fi
+
+        if [[ -z "$dotnet_dotnet_build" ]]; then
+          echo "Could not find a completed dotnet-dotnet build for branch '$(Build.SourceBranch)'"
+          exit 1
+        fi
+
+        if [[ -z "$dotnet_dotnet_sha" ]]; then
+          dotnet_dotnet_sha=$(az pipelines build show --organization 'https://dev.azure.com/v-wexu0720' --project 'Test' --id "$dotnet_dotnet_build" --query "sourceVersion" --output tsv)
+        fi
+
+        if [[ -z "$dotnet_dotnet_sha" ]]; then
+          echo "Could not find a completed dotnet-dotnet build for branch '$(Build.SourceBranch)'"
+          exit 1
+        fi
+
+        echo "Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=$dotnet_dotnet_build&view=results"
+
+        echo "##vso[build.addbuildtag]dotnet $dotnet_dotnet_sha"
+        echo "##vso[task.setvariable variable=DotnetDotnetBuildId]$dotnet_dotnet_build"
       workingDirectory: '$(Build.SourcesDirectory)'
       displayName: Find associated build
