TTT111

diff --git a/new-pipeline.yml b/new-pipeline.yml
--- a/new-pipeline.yml
+++ b/new-pipeline.yml
@@ -6,16 +6,46 @@ jobs:
 
   - script: |
       echo "Expect111111111 - alias: $(Resources.TriggeringAlias)"
-      runID=$(Resources.TriggeringAlias)_runID
-      sourceCommit=$(Resources.TriggeringAlias)_sourceCommit
 
-      echo "Actual - runID: ${!runID}"
-      echo "Actual - sourceCommit: ${!sourceCommit}"
+      dotnet_dotnet_build='${{ replace(parameters.dotnetDotnetRunId, ' ', '') }}'
+      dotnet_dotnet_sha=''
 
-      echo "##vso[task.setvariable variable=runID]$runID"
-      echo "##vso[task.setvariable variable=sourceCommit]$sourceCommit"
-    workingDirectory: '$(Build.SourcesDirectory)'
+      if [[ -z "$dotnet_dotnet_build" ]]; then
+        if [[ -z "$(Resources.TriggeringAlias)" ]]; then
+          runID=$(Resources.TriggeringAlias)_runID
+          dotnet_dotnet_build=${!runID}
+        else
+          dotnet_dotnet_build=$(az pipelines runs list --branch '$(Build.SourceBranch)' --organization '$(AZDO_ORG)' --project '$(AZDO_PROJECT)' --pipeline-ids '$(DOTNET_DOTNET_CI_PIPELINE_ID)' --status completed --top 1 --query "[].id" --output tsv)
+        fi
+      fi
+
+      if [[ -z "$dotnet_dotnet_build" ]]; then
+        echo "Could not find a completed dotnet-dotnet build for branch '$(Build.SourceBranch)'"
+        exit 1
+      fi
+
+      if [[ -z "$dotnet_dotnet_sha" ]]; then
+        if [[ -z "$(Resources.TriggeringAlias)" ]]; then
+          sourceCommit=$(Resources.TriggeringAlias)_sourceCommit
+          dotnet_dotnet_sha=${!sourceCommit}
+        else
+          dotnet_dotnet_sha=$(az pipelines build show --organization '$(AZDO_ORG)' --project '$(AZDO_PROJECT)' --id "$dotnet_dotnet_build" --query "sourceVersion" --output tsv)
+        fi
+      fi
+
+      if [[ -z "$dotnet_dotnet_sha" ]]; then
+        echo "Could not find a completed dotnet-dotnet build for branch '$(Build.SourceBranch)'"
+        exit 1
+      fi
+      
+      echo "Dotnet-dotnet build: https://dev.azure.com/dnceng/internal/_build/results?buildId=$dotnet_dotnet_build&view=results"
+
+      echo "##vso[build.addbuildtag]dotnet $dotnet_dotnet_sha"
+      echo "##vso[task.setvariable variable=DotnetDotnetBuildId]$dotnet_dotnet_build"
+
+      echo $dotnet_dotnet_sha AND $dotnet_dotnet_build
     displayName: Find associated build
+    name: Get_Build_Id
     env:
       AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
       Example_runID: $(resources.pipeline.Example.runID)
